<?php 

include('vt.php');

function bnbUsd(){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://min-api.cryptocompare.com/data/price?fsym=BNB&tsyms=USD&api_key=d4b1e2d43a9ba246bcb278bb9e47b5aca1604a5ef22e777138a84c70ba96938a');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Connection: keep-alive';
    $headers[] = 'Sec-Ch-Ua: \"Google Chrome\";v=\"95\", \"Chromium\";v=\"95\", \";Not A Brand\";v=\"99\"';
    $headers[] = 'Accept: application/json, text/plain, */*';
    $headers[] = 'Sec-Ch-Ua-Mobile: ?0';
    $headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36';
    $headers[] = 'Sec-Ch-Ua-Platform: \"macOS\"';
    $headers[] = 'Sec-Fetch-Site: same-origin';
    $headers[] = 'Sec-Fetch-Mode: cors';
    $headers[] = 'Sec-Fetch-Dest: empty';
    $headers[] = 'Referer: https://min-api.cryptocompare.com/documentation?api_key=d4b1e2d43a9ba246bcb278bb9e47b5aca1604a5ef22e777138a84c70ba96938a';
    $headers[] = 'Accept-Language: en-US,en;q=0.9,tr;q=0.8,vi;q=0.7';
    //$headers[] = 'Cookie: _ga=GA1.2.1556840488.1632521926; _ga=GA1.3.1556840488.1632521926; fbm_850963688259013=base_domain=.min-api.cryptocompare.com; auth_key=0a2662ab23467f8693b4cbd046783bf057538f8d0576dfe940971a186e185ccb; _gid=GA1.2.1115867079.1636908985; _gid=GA1.3.1115867079.1636908985';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);

    return $result;

    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

    $data = [
        'parity'    =>  bnbUsd()
    ];

    $db->table('bnbusd')->insert($data);

?>